import { parseAbi } from "viem";

export const marketplaceAbi = parseAbi([
  "error AlreadyListed()",
  "error ApprovalRevoked()",
  "error CannotBuyOwnListing()",
  "error IncorrectPayment(uint256 expected, uint256 received)",
  "error InvalidFeeRecipient()",
  "error InvalidNFTContract()",
  "error InvalidPrice()",
  "error ListingNotActive()",
  "error ListingNotFound()",
  "error MarketplaceNotApproved()",
  "error NoProceeds()",
  "error NotListingSeller()",
  "error NotTokenOwner()",
  "error PaymentTransferFailed()",
  "error ReentrancyGuardReentrantCall()",
  "error SellerNoLongerOwnsToken()",
  "event ListingCancelled(uint256 indexed listingId, address indexed seller)",
  "event NFTListed(uint256 indexed listingId, address indexed nftContract, address indexed seller, uint256 tokenId, uint256 price)",
  "event NFTSold(uint256 indexed listingId, address indexed seller, address indexed buyer, uint256 price, uint256 marketplaceFee)",
  "event ProceedsWithdrawn(address indexed account, uint256 amount)",
  "function BASIS_POINTS() view returns (uint256)",
  "function MARKETPLACE_FEE_BPS() view returns (uint256)",
  "function activeListingIdForToken(address nftContract, uint256 tokenId) view returns (uint256)",
  "function buyListing(uint256 listingId) payable",
  "function cancelListing(uint256 listingId)",
  "function createListing(address nftContract, uint256 tokenId, uint256 price) returns (uint256 listingId)",
  "function feeRecipient() view returns (address)",
  "function getListing(uint256 listingId) view returns ((uint256 listingId, address nftContract, uint256 tokenId, address seller, address buyer, uint256 price, uint8 status))",
  "function pendingProceeds(address account) view returns (uint256)",
  "function totalListings() view returns (uint256)",
  "function withdrawProceeds()",
]);
